import type { Metadata } from "next";
import { Georama } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const georama = Georama({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anime Central",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={georama.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
